httpconnpool:
    connection-request-timeout: 3000
    connection-timeout: 3000
    default-max-per-route: 20
    max-pending: 50
    max-total: 20
    socket-timeout: 3000
mybatis:
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations: classpath:sql/**/*.xml
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            auto-commit: false
            connection-test-query: select 1 from dual
            connection-timeout: 60000
        password: root
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/test
        username: root
    redis:
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
        shutdown-timeout: 100ms
      host: 127.0.0.1
      port: 6379
      ssl: false

jupiter:
  redis:
    service1:
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
        shutdown-timeout: 100ms
      host: 127.0.0.1
      port: 6379
      ssl: false
    service2:
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
        shutdown-timeout: 100ms
      host: 127.0.0.1
      port: 6380
      ssl: false      
