server:
  port: 7002
  error:
    include-exception: false
    include-stacktrace: always
    path: /error
    whitelabel:
      enabled: true
    
spring:
    application:
        name: core-jupiter-api
    profiles:
        active: local
    devtools:
      livereload:
        enabled: true
    thymeleaf:
      prefix: classpath:templates/
      suffix: .html
      check-template-location: true
      cache: false
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      generate-ddl: true

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
  - /api/v1/**